export type CommuneData = {
  tier: string
  dept?: string
  pop?: string
  volume?: string
  keyword: string
  secondaryKeywords?: string[]
  h1: string
  title: string
  description: string
  angle?: string
  wordCount: number
  cta: string
  h2s?: string[]
  intent?: string
}

export const keywordsMatrix: Record<string, CommuneData> = {
  '/': {
    tier: 'T1',
    keyword: 'gestion locative paris ouest',
    volume: '500-2k',
    secondaryKeywords: ['conciergerie paris ouest', 'agence gestion locative 92 78', 'location courte durée paris ouest'],
    h1: 'Gestion Locative Paris Ouest — Service clé en main 92 & 78',
    title: 'Gestion Locative Paris Ouest 92 & 78 — Conciergerie Paris Ouest',
    description: 'Confiez votre bien à la gestion locative #1 de Paris Ouest. Hauts-de-Seine (92) et Yvelines (78). Estimation gratuite en 48h.',
    wordCount: 2500,
    cta: 'Estimation gratuite en 48h',
  },
  '/gestion-locative-92/': {
    tier: 'T1',
    keyword: 'gestion locative 92',
    volume: '500-1k',
    secondaryKeywords: ['gestion locative hauts-de-seine', 'location courte durée 92', 'gestionnaire locatif hauts-de-seine'],
    h1: 'Gestion Locative Hauts-de-Seine (92) — Service professionnel pour propriétaires',
    title: 'Gestion Locative 92 Hauts-de-Seine | Gestion LCD — Conciergerie Paris Ouest',
    description: 'Gestion locative dans les Hauts-de-Seine (92). 36 communes couvertes. Gestion complète, revenus maximisés. Estimation gratuite.',
    wordCount: 2000,
    cta: 'Estimation gratuite 92',
    h2s: ['Nos communes dans le 92', 'Pourquoi choisir la gestion locative dans le 92', 'Estimation revenus Hauts-de-Seine', 'Nos services', 'Questions fréquentes'],
  },
  '/gestion-locative-78/': {
    tier: 'T1',
    keyword: 'gestion locative yvelines',
    volume: '200-500',
    secondaryKeywords: ['location saisonnière 78', 'gestion locative versailles yvelines', 'location courte durée 78'],
    h1: 'Gestion Locative Yvelines (78) — Location courte durée professionnelle',
    title: 'Gestion Locative 78 Yvelines | Versailles & Environs — Conciergerie Paris Ouest',
    description: 'Gestion locative dans les Yvelines (78). Versailles, Saint-Germain, Vélizy. Conciergerie professionnelle, estimation gratuite 48h.',
    wordCount: 1800,
    cta: 'Estimation gratuite 78',
    h2s: ['Nos communes dans le 78', 'Versailles et le tourisme mondial', 'Estimation revenus Yvelines', 'Nos services', 'Questions fréquentes'],
  },
  '/gestion-locative/neuilly-sur-seine/': {
    tier: 'T1', dept: '92200', pop: '62k', volume: '500-1k',
    keyword: 'gestion locative neuilly-sur-seine',
    secondaryKeywords: ['gestion locative neuilly 92200', 'location courte durée neuilly', 'agence gestion locative neuilly-sur-seine'],
    h1: 'Gestion Locative Neuilly-sur-Seine — Gestion premium, revenus maximisés',
    title: 'Gestion Locative Neuilly-sur-Seine 92200 | Gestion LCD — Conciergerie Paris Ouest',
    description: 'Gestion locative à Neuilly-sur-Seine (92200). Clientèle corporate internationale. Discrétion, profils premium. Estimation revenus gratuite.',
    angle: 'Luxe & affaires — clientèle corporate internationale, résidents aisés, discrétion, tarif/nuit parmi les plus hauts du 92',
    wordCount: 1800,
    cta: 'Estimer mes revenus à Neuilly',
    h2s: ['Pourquoi louer à Neuilly-sur-Seine', 'Estimation revenus 92200', 'Nos services de gestion locative', 'Réglementation Neuilly', 'Questions fréquentes'],
  },
  '/gestion-locative/levallois-perret/': {
    tier: 'T1', dept: '92300', pop: '68k', volume: '500-1k',
    keyword: 'gestion locative levallois-perret',
    secondaryKeywords: ['location courte durée levallois', 'gestion locative porte de champerret', 'gestion locative levallois 92300'],
    h1: 'Gestion Locative Levallois-Perret — Rentabilisez votre bien près de La Défense',
    title: 'Gestion Locative Levallois-Perret 92300 | La Défense — Conciergerie Paris Ouest',
    description: 'Gestion locative à Levallois-Perret (92300). Taux occupation semaine >85%. Clientèle corporate et consultants. Estimation gratuite 48h.',
    angle: 'Carrefour Paris–La Défense. Clientèle corporate, consultants, cadres en mission. Business traveler dominant.',
    wordCount: 1600,
    cta: 'Estimation gratuite en 48h',
    h2s: ['Pourquoi Levallois en location courte durée', 'Revenus estimés 92300', 'Notre clientèle type', 'Nos services', 'Réglementation'],
  },
  '/gestion-locative/boulogne-billancourt/': {
    tier: 'T1', dept: '92100', pop: '120k', volume: '500-1k',
    keyword: 'gestion locative boulogne-billancourt',
    secondaryKeywords: ['gestion locative boulogne 92100', 'location courte durée boulogne 92', 'location saisonnière boulogne roland garros'],
    h1: 'Gestion Locative Boulogne-Billancourt — Service clé en main 7j/7',
    title: 'Gestion Locative Boulogne-Billancourt 92100 | Roland Garros — Conciergerie Paris Ouest',
    description: 'Gestion locative à Boulogne-Billancourt (92100). Bords de Seine, Roland Garros, Île Seguin. Gestion complète. Simulez vos revenus.',
    angle: 'Bords de Seine, Île Seguin, Roland Garros. Pics de demande événementiels. Clientèle mix familles aisées + cadres.',
    wordCount: 1800,
    cta: 'Simuler mes revenus à Boulogne',
    h2s: ['Boulogne-Billancourt et la demande LCD', 'Pics Roland Garros & Île Seguin', 'Nos services de gestion locative', 'Réglementation 92100'],
  },
  '/gestion-locative/la-defense/': {
    tier: 'T1', dept: '92', volume: '200-500',
    keyword: 'gestion locative la défense',
    secondaryKeywords: ['gestion locative puteaux', 'gestion locative nanterre', 'location courte durée la défense'],
    h1: 'Gestion Locative La Défense — Puteaux, Nanterre, Courbevoie',
    title: 'Gestion Locative La Défense | Puteaux Nanterre Courbevoie — Conciergerie Paris Ouest',
    description: 'Gestion locative La Défense et communes adjacentes (Puteaux, Nanterre, Courbevoie). Demande business maximale. Estimation gratuite.',
    angle: 'Hub La Défense — demande business maximale en semaine, Paris La Défense Arena pour les pics tarifaires.',
    wordCount: 2000,
    cta: 'Estimer mes nuits La Défense',
    h2s: ['La Défense : le marché LCD le plus rentable du 92', 'Calendrier événements Arena', 'Nos zones de couverture', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/rueil-malmaison/': {
    tier: 'T1', dept: '92500', pop: '84k', volume: '200-500',
    keyword: 'gestion locative rueil-malmaison',
    secondaryKeywords: ['gestion locative rueil 92500', 'bail mobilité rueil-malmaison', 'location courte durée rueil-malmaison'],
    h1: 'Gestion Locative Rueil-Malmaison — LCD & Bail Mobilité pour propriétaires',
    title: 'Gestion Locative Rueil-Malmaison 92500 | Bail Mobilité — Conciergerie Paris Ouest',
    description: 'Gestion locative à Rueil-Malmaison (92500). Expatriés Total Energies, Sanofi, Schneider. Bail mobilité et LCD. Expert local. Estimation gratuite.',
    angle: 'Forte communauté expatriés (Total Energies, Sanofi, Schneider). Gap concurrent quasi total sur bail mobilité.',
    wordCount: 1600,
    cta: 'Parler à un expert Rueil-Malmaison',
    h2s: ['Rueil-Malmaison et ses atouts', 'Bail mobilité vs location courte durée', 'Entreprises locales et demande', 'Estimation revenus'],
  },
  '/gestion-locative/saint-cloud/': {
    tier: 'T1', dept: '92210', pop: '31k', volume: '200-500',
    keyword: 'gestion locative saint-cloud',
    secondaryKeywords: ['gestion locative saint-cloud 92210', 'location courte durée saint-cloud', 'gestion locative saint-cloud'],
    h1: "Gestion Locative Saint-Cloud — Votre bien géré dans un cadre d'exception",
    title: 'Gestion Locative Saint-Cloud 92210 | Gestion LCD — Conciergerie Paris Ouest',
    description: "Gestion locative à Saint-Cloud (92210). Résidentiel haut de gamme. Forêt et Parc. Aucun concurrent direct. Estimation gratuite.",
    angle: "Résidentiel haut de gamme, Forêt et Parc de Saint-Cloud. Aucun concurrent direct avec page dédiée.",
    wordCount: 1400,
    cta: 'Estimation gratuite Saint-Cloud',
    h2s: ['Les atouts de Saint-Cloud pour la LCD', 'Type de voyageurs', 'Nos services', 'Estimation revenus', 'Zones couvertes (Marnes, Garches)'],
  },
  '/gestion-locative/issy-les-moulineaux/': {
    tier: 'T1', dept: '92130', pop: '66k', volume: '200-500',
    keyword: 'gestion locative issy-les-moulineaux',
    secondaryKeywords: ['gestion locative issy 92130', 'location courte durée issy-les-moulineaux', 'location saisonnière issy'],
    h1: 'Gestion Locative Issy-les-Moulineaux — LCD pour propriétaires dans le hub tech',
    title: 'Gestion Locative Issy-les-Moulineaux 92130 | Hub Tech — Conciergerie Paris Ouest',
    description: 'Gestion locative à Issy-les-Moulineaux (92130). Canal+, Microsoft, Bouygues Telecom. Clientèle corporate en mission. Estimation gratuite.',
    angle: 'Hub tech/médias (Canal+, Microsoft, Bouygues Telecom, EDF). Clientèle corporate en mission.',
    wordCount: 1400,
    cta: 'Estimation gratuite Issy',
    h2s: ['Issy-les-Moulineaux hub tech', 'La demande LCD corporate', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/nanterre/': {
    tier: 'T2', dept: '92000', pop: '96k', volume: '200-500',
    keyword: 'gestion locative nanterre',
    secondaryKeywords: ['location courte durée nanterre', 'gestion locative nanterre 92000'],
    h1: 'Gestion Locative Nanterre — La Défense à portée, revenus optimisés',
    title: 'Gestion Locative Nanterre 92000 | La Défense — Conciergerie Paris Ouest',
    description: 'Gestion locative à Nanterre (92000). Porte de La Défense, RER A. Clientèle business. Estimation gratuite.',
    angle: 'Porte de La Défense. Université Paris Nanterre. Mix corporate et étudiants cadres.',
    wordCount: 1200,
    cta: 'Estimation gratuite Nanterre',
    h2s: ['Nanterre et La Défense', 'Revenus estimés', 'Nos services', 'Réglementation'],
  },
  '/gestion-locative/puteaux/': {
    tier: 'T2', dept: '92800', pop: '47k', volume: '100-300',
    keyword: 'gestion locative puteaux',
    secondaryKeywords: ['location courte durée puteaux', 'gestion locative puteaux 92800'],
    h1: 'Gestion Locative Puteaux — Au cœur de La Défense',
    title: 'Gestion Locative Puteaux 92800 | Cœur La Défense — Conciergerie Paris Ouest',
    description: 'Gestion locative à Puteaux (92800). Cœur de La Défense. Demande corporate maximale. Estimation gratuite.',
    angle: 'Cœur administratif de La Défense. Taux occupation en semaine parmi les plus élevés du 92.',
    wordCount: 1200,
    cta: 'Estimation Puteaux gratuite',
    h2s: ['Puteaux au cœur de La Défense', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/courbevoie/': {
    tier: 'T2', dept: '92400', pop: '90k', volume: '100-300',
    keyword: 'gestion locative courbevoie',
    secondaryKeywords: ['location courte durée courbevoie', 'gestion locative courbevoie 92400'],
    h1: 'Gestion Locative Courbevoie — Entre Paris et La Défense',
    title: 'Gestion Locative Courbevoie 92400 | La Défense — Conciergerie Paris Ouest',
    description: 'Gestion locative à Courbevoie (92400). Entre Paris et La Défense. Clientèle corporate. Estimation gratuite.',
    angle: 'Entre Paris et La Défense. Clientèle corporate et cadres supérieurs.',
    wordCount: 1200,
    cta: 'Estimation Courbevoie gratuite',
    h2s: ['Courbevoie entre Paris et La Défense', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/suresnes/': {
    tier: 'T2', dept: '92150', pop: '48k', volume: '100-300',
    keyword: 'gestion locative suresnes',
    secondaryKeywords: ['location courte durée suresnes', 'gestion locative suresnes 92150'],
    h1: 'Gestion Locative Suresnes — Vue sur Paris, revenus attractifs',
    title: 'Gestion Locative Suresnes 92150 | Vue Paris — Conciergerie Paris Ouest',
    description: 'Gestion locative à Suresnes (92150). Vue panoramique sur Paris. Bois de Boulogne. Estimation gratuite.',
    angle: 'Vue sur Paris, Bois de Boulogne adjacent. Clientèle cherchant le calme avec proximité Paris.',
    wordCount: 1000,
    cta: 'Estimation Suresnes gratuite',
    h2s: ['Les atouts de Suresnes', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/garches/': {
    tier: 'T3', dept: '92380', pop: '19k', volume: '50-200',
    keyword: 'gestion locative garches',
    secondaryKeywords: ['location courte durée garches', 'gestion locative garches 92380'],
    h1: 'Gestion Locative Garches — Résidentiel premium, calme garanti',
    title: 'Gestion Locative Garches 92380 | Résidentiel Premium — Conciergerie Paris Ouest',
    description: 'Gestion locative à Garches (92380). Résidentiel haut de gamme. Forêt de Fausses Reposes. Estimation gratuite.',
    angle: 'Résidentiel exclusif. Voisinage Saint-Cloud. Clientèle aisée cherchant calme et prestige.',
    wordCount: 800,
    cta: 'Estimation Garches gratuite',
    h2s: ['Garches résidentiel premium', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/la-garenne-colombes/': {
    tier: 'T3', dept: '92250', pop: '29k', volume: '50-200',
    keyword: 'gestion locative la garenne-colombes',
    secondaryKeywords: ['location courte durée la garenne-colombes', 'gestion locative la garenne 92250'],
    h1: 'Gestion Locative La Garenne-Colombes — Proche La Défense',
    title: 'Gestion Locative La Garenne-Colombes 92250 | La Défense — Conciergerie Paris Ouest',
    description: 'Gestion locative à La Garenne-Colombes (92250). Proche La Défense. Familial et calme. Estimation gratuite.',
    angle: 'Quartier résidentiel familial à 5 min de La Défense. Prix attractifs pour propriétaires.',
    wordCount: 800,
    cta: 'Estimation La Garenne-Colombes',
    h2s: ['La Garenne-Colombes et La Défense', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/vaucresson/': {
    tier: 'T4', dept: '92420', pop: '8k', volume: '20-100',
    keyword: 'gestion locative vaucresson',
    secondaryKeywords: ['location courte durée vaucresson', 'gestion locative vaucresson 92420'],
    h1: 'Gestion Locative Vaucresson — Niche premium Paris Ouest',
    title: 'Gestion Locative Vaucresson 92420 | Premium — Conciergerie Paris Ouest',
    description: 'Gestion locative à Vaucresson (92420). Résidentiel haut de gamme. Forêt de Fausses Reposes. Estimation gratuite.',
    angle: 'Village aisé entre Saint-Cloud et Versailles. Clientèle très haut de gamme.',
    wordCount: 600,
    cta: 'Estimation Vaucresson gratuite',
    h2s: ['Vaucresson résidentiel exclusif', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/montrouge/': {
    tier: 'T2', dept: '92120', pop: '50k', volume: '200-500',
    keyword: 'gestion locative montrouge',
    secondaryKeywords: ['location courte durée montrouge', 'gestion locative montrouge 92120'],
    h1: 'Gestion Locative Montrouge — Gestion LCD à deux pas de Paris',
    title: 'Gestion Locative Montrouge 92120 | Porte Paris 14e — Conciergerie Paris Ouest',
    description: 'Gestion locative à Montrouge (92120). Métro 4 direct centre Paris. Clientèle jeune et professionnelle. Estimation gratuite.',
    angle: 'Limite Paris 14e. Métro 4 direct. Prix propriétaire plus attractif qu\'intramuros.',
    wordCount: 1200,
    cta: 'Estimation Montrouge gratuite',
    h2s: ['Montrouge et la demande LCD', 'Revenus vs Paris 14e', 'Nos services', 'Réglementation'],
  },
  '/gestion-locative/malakoff/': {
    tier: 'T2', dept: '92240', pop: '31k', volume: '100-300',
    keyword: 'gestion locative malakoff',
    secondaryKeywords: ['location courte durée malakoff', 'gestion locative malakoff 92240'],
    h1: 'Gestion Locative Malakoff — Porte de Paris, LCD rentable',
    title: 'Gestion Locative Malakoff 92240 | Porte Paris — Conciergerie Paris Ouest',
    description: 'Gestion locative à Malakoff (92240). Frontière Paris 14e/15e. Métro direct. Estimation gratuite.',
    angle: 'Frontière Paris. Prix propriétaire 92 pour clientèle cherchant la proximité Paris.',
    wordCount: 1000,
    cta: 'Estimation Malakoff gratuite',
    h2s: ['Malakoff porte de Paris', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/asnieres-sur-seine/': {
    tier: 'T2', dept: '92600', pop: '88k', volume: '200-500',
    keyword: 'gestion locative asnières-sur-seine',
    secondaryKeywords: ['location courte durée asnières', 'gestion locative asnières 92600'],
    h1: 'Gestion Locative Asnières-sur-Seine — Bords de Seine, revenus attractifs',
    title: 'Gestion Locative Asnières-sur-Seine 92600 | Bords Seine — Conciergerie Paris Ouest',
    description: 'Gestion locative à Asnières-sur-Seine (92600). Bords de Seine. Métro 13. Clientèle diversifiée. Estimation gratuite.',
    angle: 'Bords de Seine, métro 13 direct Paris. Bon rapport location/prix pour propriétaires.',
    wordCount: 1000,
    cta: 'Estimation Asnières gratuite',
    h2s: ['Asnières-sur-Seine et la LCD', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/colombes/': {
    tier: 'T3', dept: '92700', pop: '88k', volume: '100-300',
    keyword: 'gestion locative colombes',
    secondaryKeywords: ['location courte durée colombes', 'gestion locative colombes 92700'],
    h1: 'Gestion Locative Colombes — Proche La Défense, prix attractifs',
    title: 'Gestion Locative Colombes 92700 | La Défense — Conciergerie Paris Ouest',
    description: 'Gestion locative à Colombes (92700). Proche La Défense. Prix propriétaires attractifs. Estimation gratuite.',
    angle: 'Ville accessible proche de La Défense. Bon potentiel LCD pour propriétaires.',
    wordCount: 800,
    cta: 'Estimation Colombes gratuite',
    h2s: ['Colombes et la LCD', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/clichy/': {
    tier: 'T2', dept: '92110', pop: '62k', volume: '200-500',
    keyword: 'gestion locative clichy',
    secondaryKeywords: ['location courte durée clichy', 'gestion locative porte de clichy 92110'],
    h1: 'Gestion Locative Clichy — Location courte durée à la frontière de Paris',
    title: 'Gestion Locative Clichy 92110 | Porte Paris 17e — Conciergerie Paris Ouest',
    description: 'Gestion locative à Clichy (92110). Frontière Paris 17e. Métro 13. Prix propriétaire 92 pour clientèle aux tarifs Paris. Estimation gratuite.',
    angle: 'Frontière Paris 17e. Prix propriétaire 92 pour clientèle qui paye les prix Paris.',
    wordCount: 1200,
    cta: 'Estimation Clichy gratuite',
    h2s: ['Clichy porte de Paris', 'Revenus LCD', 'Nos services', 'Réglementation'],
  },
  '/gestion-locative/gennevilliers/': {
    tier: 'T3', dept: '92230', pop: '47k', volume: '50-200',
    keyword: 'gestion locative gennevilliers',
    secondaryKeywords: ['location courte durée gennevilliers', 'gestion locative gennevilliers 92230'],
    h1: 'Gestion Locative Gennevilliers — LCD dans le 92 Nord',
    title: 'Gestion Locative Gennevilliers 92230 — Conciergerie Paris Ouest',
    description: 'Gestion locative à Gennevilliers (92230). Bords de Seine. Proche Asnières. Estimation gratuite.',
    angle: 'Zone en développement. Prix propriétaires bas, potentiel de rendement élevé.',
    wordCount: 700,
    cta: 'Estimation Gennevilliers gratuite',
    h2s: ['Gennevilliers et la LCD', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/bois-colombes/': {
    tier: 'T3', dept: '92270', pop: '29k', volume: '50-200',
    keyword: 'gestion locative bois-colombes',
    secondaryKeywords: ['location courte durée bois-colombes', 'gestion locative bois-colombes 92270'],
    h1: 'Gestion Locative Bois-Colombes — Résidentiel calme proche La Défense',
    title: 'Gestion Locative Bois-Colombes 92270 | La Défense — Conciergerie Paris Ouest',
    description: 'Gestion locative à Bois-Colombes (92270). Résidentiel calme. Proche La Défense. Estimation gratuite.',
    angle: 'Commune résidentielle tranquille à 10 min de La Défense. Clientèle corporate cherchant le calme.',
    wordCount: 700,
    cta: 'Estimation Bois-Colombes gratuite',
    h2s: ['Bois-Colombes résidentiel', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/chatillon/': {
    tier: 'T3', dept: '92320', pop: '37k', volume: '50-200',
    keyword: 'gestion locative châtillon',
    secondaryKeywords: ['location courte durée châtillon', 'gestion locative châtillon 92320'],
    h1: 'Gestion Locative Châtillon — LCD dans le Sud 92',
    title: 'Gestion Locative Châtillon 92320 | Sud 92 — Conciergerie Paris Ouest',
    description: 'Gestion locative à Châtillon (92320). Sud des Hauts-de-Seine. Métro 13. Estimation gratuite.',
    angle: 'Commune du Sud 92, métro 13. Clientèle mixte cherchant la proximité Paris.',
    wordCount: 700,
    cta: 'Estimation Châtillon gratuite',
    h2s: ['Châtillon et la LCD', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/clamart/': {
    tier: 'T3', dept: '92140', pop: '54k', volume: '50-200',
    keyword: 'gestion locative clamart',
    secondaryKeywords: ['location courte durée clamart', 'gestion locative clamart 92140'],
    h1: 'Gestion Locative Clamart — LCD dans le 92 Sud-Ouest',
    title: 'Gestion Locative Clamart 92140 | Sud-Ouest 92 — Conciergerie Paris Ouest',
    description: 'Gestion locative à Clamart (92140). Forêt de Meudon. Proche Issy et Meudon. Estimation gratuite.',
    angle: 'Proche forêt de Meudon. Résidentiel et vert. Clientèle cherchant cadre agréable.',
    wordCount: 800,
    cta: 'Estimation Clamart gratuite',
    h2s: ['Clamart et la LCD', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/antony/': {
    tier: 'T3', dept: '92160', pop: '61k', volume: '50-200',
    keyword: 'gestion locative antony',
    secondaryKeywords: ['location courte durée antony', 'gestion locative antony 92160'],
    h1: 'Gestion Locative Antony — Pôle étudiant et corporate du Sud 92',
    title: 'Gestion Locative Antony 92160 | Sud 92 — Conciergerie Paris Ouest',
    description: 'Gestion locative à Antony (92160). Pôle universitaire et scientifique. RER B. Estimation gratuite.',
    angle: 'Pôle universitaire (campus HEC adjacent) et scientifique. RER B direct Orly et Paris.',
    wordCount: 800,
    cta: 'Estimation Antony gratuite',
    h2s: ['Antony pôle universitaire', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/chatenay-malabry/': {
    tier: 'T3', dept: '92290', pop: '32k', volume: '30-150',
    keyword: 'gestion locative châtenay-malabry',
    secondaryKeywords: ['location courte durée châtenay', 'gestion locative châtenay 92290'],
    h1: 'Gestion Locative Châtenay-Malabry — LCD dans un écrin de verdure',
    title: 'Gestion Locative Châtenay-Malabry 92290 — Conciergerie Paris Ouest',
    description: 'Gestion locative à Châtenay-Malabry (92290). Parc de Sceaux voisin. Résidentiel vert. Estimation gratuite.',
    angle: 'Voisinage Parc de Sceaux. Résidentiel verdoyant. Clientèle cherchant nature et proximité Paris.',
    wordCount: 700,
    cta: 'Estimation Châtenay-Malabry gratuite',
    h2s: ['Châtenay-Malabry et la LCD', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/vanves/': {
    tier: 'T2', dept: '92170', pop: '27k', volume: '100-300',
    keyword: 'gestion locative vanves',
    secondaryKeywords: ['location courte durée vanves', 'gestion locative vanves 92170'],
    h1: 'Gestion Locative Vanves — Frontière Paris 15e, LCD rentable',
    title: 'Gestion Locative Vanves 92170 | Porte Paris 15e — Conciergerie Paris Ouest',
    description: 'Gestion locative à Vanves (92170). Frontière Paris 15e. Tramway T3. Estimation gratuite.',
    angle: 'Frontière Paris 15e. Tramway T3. Prix propriétaire attractif pour clientèle Paris.',
    wordCount: 1000,
    cta: 'Estimation Vanves gratuite',
    h2s: ['Vanves porte de Paris', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/meudon/': {
    tier: 'T2', dept: '92190', pop: '44k', volume: '100-300',
    keyword: 'gestion locative meudon',
    secondaryKeywords: ['location courte durée meudon', 'gestion locative meudon 92190'],
    h1: 'Gestion Locative Meudon — Forêt, Seine et revenus optimisés',
    title: 'Gestion Locative Meudon 92190 | Forêt & Seine — Conciergerie Paris Ouest',
    description: 'Gestion locative à Meudon (92190). Forêt de Meudon, bords de Seine. Résidentiel haut de gamme. Estimation gratuite.',
    angle: 'Forêt de Meudon, observatoire. Résidentiel haut de gamme. Liaison Versailles (forêt de Fausses Reposes).',
    wordCount: 1000,
    cta: 'Estimation Meudon gratuite',
    h2s: ['Meudon entre forêt et Seine', 'Revenus estimés', 'Nos services', 'Réglementation'],
  },
  '/gestion-locative/sevres/': {
    tier: 'T2', dept: '92310', pop: '24k', volume: '100-300',
    keyword: 'gestion locative sèvres',
    secondaryKeywords: ['location courte durée sèvres', 'gestion locative sèvres 92310'],
    h1: 'Gestion Locative Sèvres — Prestige entre Paris et Versailles',
    title: 'Gestion Locative Sèvres 92310 | Entre Paris & Versailles — Conciergerie Paris Ouest',
    description: 'Gestion locative à Sèvres (92310). Manufacture de Sèvres. Entre Paris et Versailles. Estimation gratuite.',
    angle: 'Manufacture de porcelaine de Sèvres, bords de Seine. Entre Paris et Versailles. Clientèle haut de gamme.',
    wordCount: 1000,
    cta: 'Estimation Sèvres gratuite',
    h2s: ['Sèvres entre Paris et Versailles', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/chaville/': {
    tier: 'T3', dept: '92370', pop: '19k', volume: '30-150',
    keyword: 'gestion locative chaville',
    secondaryKeywords: ['location courte durée chaville', 'gestion locative chaville 92370'],
    h1: 'Gestion Locative Chaville — Entre forêt et Versailles',
    title: 'Gestion Locative Chaville 92370 — Conciergerie Paris Ouest',
    description: 'Gestion locative à Chaville (92370). Forêt de Fausses Reposes. Entre Sèvres et Versailles. Estimation gratuite.',
    angle: 'Forêt de Fausses Reposes. Liaison directe Versailles. Cadre naturel exceptionnel.',
    wordCount: 700,
    cta: 'Estimation Chaville gratuite',
    h2s: ['Chaville entre nature et histoire', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/marnes-la-coquette/': {
    tier: 'T4', dept: '92430', pop: '1700', volume: '10-50',
    keyword: 'gestion locative marnes-la-coquette',
    secondaryKeywords: ['location courte durée marnes-la-coquette', 'gestion locative marnes 92430'],
    h1: 'Gestion Locative Marnes-la-Coquette — Exclusivité absolue dans le 92',
    title: 'Gestion Locative Marnes-la-Coquette 92430 | Ultra-Premium — Conciergerie Paris Ouest',
    description: 'Gestion locative à Marnes-la-Coquette (92430). Village le plus cher du 92. Clientèle ultra-premium. Estimation gratuite.',
    angle: 'Village le plus petit et le plus haut de gamme du 92. Clientèle ultra-premium. Tarifs parmi les plus élevés.',
    wordCount: 600,
    cta: 'Estimation Marnes-la-Coquette gratuite',
    h2s: ['Marnes-la-Coquette exclusivité', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/ville-d-avray/': {
    tier: 'T3', dept: '92410', pop: '11k', volume: '20-100',
    keyword: 'gestion locative ville-d\'avray',
    secondaryKeywords: ['location courte durée ville-d\'avray', 'gestion locative ville d avray 92410'],
    h1: 'Gestion Locative Ville-d\'Avray — Les étangs de Corot, LCD premium',
    title: 'Gestion Locative Ville-d\'Avray 92410 | Étangs de Corot — Conciergerie Paris Ouest',
    description: 'Gestion locative à Ville-d\'Avray (92410). Étangs de Corot. Forêt de Fausses Reposes. Estimation gratuite.',
    angle: 'Étangs de Corot (patrimoine artistique). Forêt et nature. Clientèle cultivée cherchant le prestige discret.',
    wordCount: 700,
    cta: 'Estimation Ville-d\'Avray gratuite',
    h2s: ['Ville-d\'Avray et les étangs de Corot', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/bagneux/': {
    tier: 'T4', dept: '92220', pop: '40k', volume: '30-150',
    keyword: 'gestion locative bagneux',
    secondaryKeywords: ['location courte durée bagneux', 'gestion locative bagneux 92220'],
    h1: 'Gestion Locative Bagneux — LCD dans le 92 Sud accessible',
    title: 'Gestion Locative Bagneux 92220 — Conciergerie Paris Ouest',
    description: 'Gestion locative à Bagneux (92220). Métro 4 prolongé. Proche Montrouge et Paris. Estimation gratuite.',
    angle: 'Extension métro 4. En développement. Bon potentiel locatif à prix propriétaire accessible.',
    wordCount: 600,
    cta: 'Estimation Bagneux gratuite',
    h2s: ['Bagneux et le métro 4', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/fontenay-aux-roses/': {
    tier: 'T4', dept: '92260', pop: '23k', volume: '20-100',
    keyword: 'gestion locative fontenay-aux-roses',
    secondaryKeywords: ['location courte durée fontenay-aux-roses', 'gestion locative fontenay 92260'],
    h1: 'Gestion Locative Fontenay-aux-Roses — Village fleuri, revenus optimisés',
    title: 'Gestion Locative Fontenay-aux-Roses 92260 — Conciergerie Paris Ouest',
    description: 'Gestion locative à Fontenay-aux-Roses (92260). Village fleuri, parc de Sceaux adjacent. Estimation gratuite.',
    angle: 'Village fleuri historique. Parc de Sceaux à deux pas. Clientèle cherchant le charme de la campagne proche Paris.',
    wordCount: 600,
    cta: 'Estimation Fontenay-aux-Roses gratuite',
    h2s: ['Fontenay-aux-Roses village fleuri', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/le-plessis-robinson/': {
    tier: 'T4', dept: '92350', pop: '28k', volume: '20-100',
    keyword: 'gestion locative le plessis-robinson',
    secondaryKeywords: ['location courte durée le plessis-robinson', 'gestion locative plessis 92350'],
    h1: 'Gestion Locative Le Plessis-Robinson — LCD dans le 92 Sud',
    title: 'Gestion Locative Le Plessis-Robinson 92350 — Conciergerie Paris Ouest',
    description: 'Gestion locative au Plessis-Robinson (92350). Proche Antony et Châtenay. Résidentiel calme. Estimation gratuite.',
    angle: 'Commune résidentielle dans le sud 92. Proche Antony (RER B) et Châtenay-Malabry.',
    wordCount: 600,
    cta: 'Estimation Le Plessis-Robinson gratuite',
    h2s: ['Le Plessis-Robinson et la LCD', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/sceaux/': {
    tier: 'T3', dept: '92330', pop: '20k', volume: '50-200',
    keyword: 'gestion locative sceaux',
    secondaryKeywords: ['location courte durée sceaux', 'gestion locative sceaux 92330'],
    h1: 'Gestion Locative Sceaux — Parc, prestige et revenus locatifs',
    title: 'Gestion Locative Sceaux 92330 | Parc de Sceaux — Conciergerie Paris Ouest',
    description: 'Gestion locative à Sceaux (92330). Parc de Sceaux, château. Résidentiel haut de gamme. Estimation gratuite.',
    angle: 'Parc de Sceaux (châteaux, orangerie). Résidentiel haut de gamme. Clientèle culturelle et aisée.',
    wordCount: 800,
    cta: 'Estimation Sceaux gratuite',
    h2s: ['Sceaux et son parc prestigieux', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/bourg-la-reine/': {
    tier: 'T3', dept: '92340', pop: '21k', volume: '50-200',
    keyword: 'gestion locative bourg-la-reine',
    secondaryKeywords: ['location courte durée bourg-la-reine', 'gestion locative bourg la reine 92340'],
    h1: 'Gestion Locative Bourg-la-Reine — RER B, LCD accessible',
    title: 'Gestion Locative Bourg-la-Reine 92340 | RER B — Conciergerie Paris Ouest',
    description: 'Gestion locative à Bourg-la-Reine (92340). RER B direct Paris. Proche Sceaux et Antony. Estimation gratuite.',
    angle: 'RER B direct (Paris en 15 min). Commune résidentielle agréable dans le sud 92.',
    wordCount: 700,
    cta: 'Estimation Bourg-la-Reine gratuite',
    h2s: ['Bourg-la-Reine et le RER B', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/versailles/': {
    tier: 'T1', dept: '78000', pop: '88k', volume: '500-2k',
    keyword: 'gestion locative versailles',
    secondaryKeywords: ['location saisonnière versailles', 'gestion locative versailles grandes eaux', 'gestion locative yvelines versailles'],
    h1: 'Gestion Locative Versailles — Maximisez vos revenus toute l\'année',
    title: 'Gestion Locative Versailles 78000 | Grandes Eaux & Tourisme — Conciergerie Paris Ouest',
    description: 'Gestion locative à Versailles (78000). Château, Grandes Eaux, congrès. Tarification événementielle. Voyageurs internationaux. Estimation gratuite.',
    angle: 'Château + tourisme mondial + congrès. Peaks Grandes Eaux. Tarification événementielle. Voyageurs internationaux EN/ES/ZH.',
    wordCount: 2000,
    cta: 'Voir le calendrier de tarification Versailles',
    h2s: ['Le marché gestion locative à Versailles', 'Calendrier événementiel et tarification', 'Gestion voyageurs internationaux', 'Nos services', 'Réglementation 78'],
  },
  '/gestion-locative/le-chesnay-rocquencourt/': {
    tier: 'T1', dept: '78150', pop: '28k', volume: '100-300',
    keyword: 'gestion locative le chesnay-rocquencourt',
    secondaryKeywords: ['location courte durée le chesnay', 'gestion locative chesnay 78150'],
    h1: 'Gestion Locative Le Chesnay-Rocquencourt — Aux portes de Versailles',
    title: 'Gestion Locative Le Chesnay-Rocquencourt 78150 | Versailles — Conciergerie Paris Ouest',
    description: 'Gestion locative au Chesnay-Rocquencourt (78150). Aux portes du château de Versailles. Estimation gratuite.',
    angle: 'Aux portes du Château de Versailles. Partage le flux touristique versaillais.',
    wordCount: 1200,
    cta: 'Estimation Le Chesnay-Rocquencourt',
    h2s: ['Le Chesnay-Rocquencourt aux portes de Versailles', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/viroflay/': {
    tier: 'T1', dept: '78220', pop: '16k', volume: '50-200',
    keyword: 'gestion locative viroflay',
    secondaryKeywords: ['location courte durée viroflay', 'gestion locative viroflay 78220'],
    h1: 'Gestion Locative Viroflay — Entre Versailles et Paris',
    title: 'Gestion Locative Viroflay 78220 | Versailles & Meudon — Conciergerie Paris Ouest',
    description: 'Gestion locative à Viroflay (78220). Entre Versailles et Paris. Forêt de Fausses Reposes. Estimation gratuite.',
    angle: 'Nœud entre Versailles et Meudon (forêt de Fausses Reposes). RER C et Transilien.',
    wordCount: 1200,
    cta: 'Estimation Viroflay gratuite',
    h2s: ['Viroflay entre Versailles et Paris', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/velizy-villacoublay/': {
    tier: 'T1', dept: '78140', pop: '22k', volume: '100-300',
    keyword: 'gestion locative vélizy-villacoublay',
    secondaryKeywords: ['gestion locative vélizy 78140', 'location courte durée vélizy', 'location saisonnière vélizy'],
    h1: 'Gestion Locative Vélizy-Villacoublay — Gestion LCD dans le hub aérospatial',
    title: 'Gestion Locative Vélizy-Villacoublay 78140 | Thales Dassault — Conciergerie Paris Ouest',
    description: 'Gestion locative à Vélizy-Villacoublay (78140). Thales, Dassault, Boeing. Taux occupation semaine exceptionnel. Estimation gratuite.',
    angle: "Thales, Dassault Aviation, Boeing, Airbus Defence. Demande business massive en semaine.",
    wordCount: 1400,
    cta: 'Estimation Vélizy gratuite',
    h2s: ['Hub aérospatial et demande LCD', 'Revenus estimés', 'Nos services', 'Clients cibles Vélizy'],
  },
  '/gestion-locative/la-celle-saint-cloud/': {
    tier: 'T2', dept: '78170', pop: '22k', volume: '50-200',
    keyword: 'gestion locative la celle-saint-cloud',
    secondaryKeywords: ['location courte durée la celle-saint-cloud', 'gestion locative celle saint cloud 78170'],
    h1: 'Gestion Locative La Celle-Saint-Cloud — Résidentiel haut de gamme dans le 78',
    title: 'Gestion Locative La Celle-Saint-Cloud 78170 — Conciergerie Paris Ouest',
    description: 'Gestion locative à La Celle-Saint-Cloud (78170). Résidentiel aisé. Proche Versailles et Saint-Cloud. Estimation gratuite.',
    angle: 'Résidentiel haut de gamme. Intersection silo 92 (Saint-Cloud) et silo 78 (Versailles).',
    wordCount: 1000,
    cta: 'Estimation La Celle-Saint-Cloud',
    h2s: ['La Celle-Saint-Cloud résidentiel premium', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/bougival/': {
    tier: 'T2', dept: '78380', pop: '9k', volume: '50-200',
    keyword: 'gestion locative bougival',
    secondaryKeywords: ['location courte durée bougival', 'gestion locative bougival 78380'],
    h1: 'Gestion Locative Bougival — Les impressionnistes et la LCD premium',
    title: 'Gestion Locative Bougival 78380 | Bords de Seine — Conciergerie Paris Ouest',
    description: 'Gestion locative à Bougival (78380). Bords de Seine des impressionnistes. Rueil et Versailles proches. Estimation gratuite.',
    angle: "Bords de Seine des impressionnistes. Charme historique unique. Tourisme culturel et clientèle haut de gamme.",
    wordCount: 1000,
    cta: 'Estimation Bougival gratuite',
    h2s: ['Bougival et les impressionnistes', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/jouy-en-josas/': {
    tier: 'T3', dept: '78350', pop: '8k', volume: '20-100',
    keyword: 'gestion locative jouy-en-josas',
    secondaryKeywords: ['location courte durée jouy-en-josas', 'gestion locative jouy 78350'],
    h1: 'Gestion Locative Jouy-en-Josas — Campus HEC, demande Corporate',
    title: 'Gestion Locative Jouy-en-Josas 78350 | HEC Campus — Conciergerie Paris Ouest',
    description: 'Gestion locative à Jouy-en-Josas (78350). Campus HEC Paris. Chercheurs et cadres. Estimation gratuite.',
    angle: 'Campus HEC Paris. Chercheurs INRAE. Clientèle académique et corporate internationale.',
    wordCount: 700,
    cta: 'Estimation Jouy-en-Josas gratuite',
    h2s: ['Jouy-en-Josas campus HEC', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/saint-germain-en-laye/': {
    tier: 'T1', dept: '78100', pop: '40k', volume: '200-500',
    keyword: 'gestion locative saint-germain-en-laye',
    secondaryKeywords: ['gestion locative saint-germain 78100', 'location courte durée saint-germain-en-laye', 'location saisonnière saint-germain'],
    h1: 'Gestion Locative Saint-Germain-en-Laye — Gestion LCD dans la ville royale',
    title: 'Gestion Locative Saint-Germain-en-Laye 78100 | RER A — Conciergerie Paris Ouest',
    description: 'Gestion locative à Saint-Germain-en-Laye (78100). Château royal, forêt, RER A direct. Forte communauté anglophone. Estimation gratuite.',
    angle: 'Château royal (Debussy), forêt, terrasse sur Paris. RER A direct. Tourisme fort + clientèle expatriés anglophones.',
    wordCount: 1600,
    cta: 'Estimation gratuite Saint-Germain',
    h2s: ['Saint-Germain-en-Laye atouts touristiques', 'Revenus estimés', 'Nos services', 'Réglementation 78100'],
  },
  '/gestion-locative/poissy/': {
    tier: 'T2', dept: '78300', pop: '38k', volume: '50-200',
    keyword: 'gestion locative poissy',
    secondaryKeywords: ['location courte durée poissy', 'gestion locative poissy 78300'],
    h1: 'Gestion Locative Poissy — Villa Savoye, patrimoine et LCD',
    title: 'Gestion Locative Poissy 78300 | Villa Savoye — Conciergerie Paris Ouest',
    description: 'Gestion locative à Poissy (78300). Villa Savoye (Le Corbusier). Bords de Seine. Estimation gratuite.',
    angle: 'Villa Savoye (patrimoine UNESCO). Bords de Seine. Industrie automobile (Stellantis).',
    wordCount: 1000,
    cta: 'Estimation Poissy gratuite',
    h2s: ['Poissy patrimoine et industrie', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/maisons-laffitte/': {
    tier: 'T2', dept: '78600', pop: '23k', volume: '50-200',
    keyword: 'gestion locative maisons-laffitte',
    secondaryKeywords: ['location courte durée maisons-laffitte', 'gestion locative maisons laffitte 78600'],
    h1: 'Gestion Locative Maisons-Laffitte — Hippodrome, prestige et revenus',
    title: 'Gestion Locative Maisons-Laffitte 78600 | Hippodrome — Conciergerie Paris Ouest',
    description: 'Gestion locative à Maisons-Laffitte (78600). Hippodrome, château, bords de Seine. Estimation gratuite.',
    angle: 'Hippodrome de Maisons-Laffitte. Château. Bords de Seine. Pics tarifaires lors des courses.',
    wordCount: 1000,
    cta: 'Estimation Maisons-Laffitte gratuite',
    h2s: ['Maisons-Laffitte hippodrome et château', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/conflans-sainte-honorine/': {
    tier: 'T3', dept: '78700', pop: '35k', volume: '20-100',
    keyword: 'gestion locative conflans-sainte-honorine',
    secondaryKeywords: ['location courte durée conflans', 'gestion locative conflans 78700'],
    h1: 'Gestion Locative Conflans-Sainte-Honorine — Confluent Seine et Oise',
    title: 'Gestion Locative Conflans-Sainte-Honorine 78700 — Conciergerie Paris Ouest',
    description: 'Gestion locative à Conflans-Sainte-Honorine (78700). Confluent Seine et Oise. Batellerie. Estimation gratuite.',
    angle: 'Ville des mariniers. Confluent Seine et Oise. Tourisme fluvial et clientèle cherchant authenticité.',
    wordCount: 700,
    cta: 'Estimation Conflans gratuite',
    h2s: ['Conflans-Sainte-Honorine et la batellerie', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/louveciennes/': {
    tier: 'T3', dept: '78430', pop: '7k', volume: '20-100',
    keyword: 'gestion locative louveciennes',
    secondaryKeywords: ['location courte durée louveciennes', 'gestion locative louveciennes 78430'],
    h1: 'Gestion Locative Louveciennes — Impressionnistes et prestige discret',
    title: 'Gestion Locative Louveciennes 78430 | Impressionnistes — Conciergerie Paris Ouest',
    description: 'Gestion locative à Louveciennes (78430). Village des impressionnistes. Voisinage Versailles. Estimation gratuite.',
    angle: "Village des impressionnistes (Pissarro, Renoir). Proche Versailles et Marly. Charme village de prestige.",
    wordCount: 700,
    cta: 'Estimation Louveciennes gratuite',
    h2s: ['Louveciennes village impressionniste', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/marly-le-roi/': {
    tier: 'T3', dept: '78160', pop: '16k', volume: '20-100',
    keyword: 'gestion locative marly-le-roi',
    secondaryKeywords: ['location courte durée marly-le-roi', 'gestion locative marly 78160'],
    h1: 'Gestion Locative Marly-le-Roi — Forêt royale et prestige',
    title: 'Gestion Locative Marly-le-Roi 78160 | Forêt Royale — Conciergerie Paris Ouest',
    description: 'Gestion locative à Marly-le-Roi (78160). Forêt de Marly (ancienne résidence royale). Prestige discret. Estimation gratuite.',
    angle: 'Forêt royale de Marly. Ancien domaine royal. Clientèle cherchant prestige historique et nature.',
    wordCount: 700,
    cta: 'Estimation Marly-le-Roi gratuite',
    h2s: ['Marly-le-Roi forêt royale', 'Revenus estimés', 'Nos services'],
  },
  '/gestion-locative/le-pecq/': {
    tier: 'T3', dept: '78230', pop: '16k', volume: '20-100',
    keyword: 'gestion locative le pecq',
    secondaryKeywords: ['location courte durée le pecq', 'gestion locative le pecq 78230'],
    h1: 'Gestion Locative Le Pecq — Bords de Seine, voisin de Saint-Germain',
    title: 'Gestion Locative Le Pecq 78230 | Saint-Germain — Conciergerie Paris Ouest',
    description: 'Gestion locative au Pecq (78230). Bords de Seine. Voisin de Saint-Germain-en-Laye. Estimation gratuite.',
    angle: 'Rive gauche de Saint-Germain-en-Laye. Bords de Seine. Profite du flux touristique voisin.',
    wordCount: 700,
    cta: 'Estimation Le Pecq gratuite',
    h2s: ['Le Pecq voisin de Saint-Germain', 'Revenus estimés', 'Nos services'],
  },
  '/blog/rentabilite-gestion-locative-92/': {
    tier: 'T1', intent: 'informationnel',
    keyword: 'combien rapporte gestion locative dans le 92',
    secondaryKeywords: ['rendement location courte durée 92', 'revenus gestion locative hauts-de-seine'],
    h1: 'Combien rapporte un bien en gestion locative dans le 92 en 2026 ? Guide complet par commune',
    title: 'Revenus gestion locative 92 en 2026 : tableau par commune | Conciergerie Paris Ouest',
    description: 'Combien rapporte votre bien en gestion locative dans les Hauts-de-Seine ? Tableau de rentabilité par commune, données 2026.',
    wordCount: 2500,
    cta: 'Calculer mes revenus',
  },
  '/blog/reglementation-location-paris-ouest/': {
    tier: 'T1', intent: 'informationnel',
    keyword: 'réglementation gestion locative paris ouest 2026',
    secondaryKeywords: ['enregistrement location courte durée', 'règle 120 jours gestion locative'],
    h1: 'Réglementation location courte durée Paris Ouest 2026 — Guide complet',
    title: 'Réglementation gestion locative Paris Ouest 2026 : 92, 78 | Conciergerie Paris Ouest',
    description: 'Tout sur la réglementation gestion locative en 2026 : enregistrement, règle 120 jours, DPE, copropriété. Guide complet Paris Ouest.',
    wordCount: 2000,
    cta: 'Parler à un expert réglementation',
  },
  '/blog/investir-lcd-78/': {
    tier: 'T1', intent: 'informationnel',
    keyword: 'investir location courte durée yvelines',
    secondaryKeywords: ['rendement lcd versailles yvelines', 'investissement gestion locative 78'],
    h1: 'Investir en Location Courte Durée dans les Yvelines (78) : Guide 2026',
    title: 'Investir LCD Yvelines (78) 2026 : Versailles, Vélizy, Saint-Germain | Conciergerie Paris Ouest',
    description: 'Guide complet pour investir en location courte durée dans les Yvelines en 2026. Versailles, Vélizy, Saint-Germain. Rentabilité, fiscalité.',
    wordCount: 2500,
    cta: 'Estimer mon projet 78',
  },
  '/blog/tarifs-conciergerie/': {
    tier: 'T1', intent: 'informationnel',
    keyword: 'commission gestion locative paris',
    secondaryKeywords: ['tarif gestion locative paris ouest', 'prix conciergerie'],
    h1: "Tarifs et Commissions d'une Conciergerie à Paris Ouest",
    title: 'Tarifs Conciergerie Paris Ouest 2026 : Commissions & Services | Conciergerie Paris Ouest',
    description: "Quels sont les tarifs d'une gestion locative à Paris Ouest ? Commissions, services inclus, comparaison. Transparence totale.",
    wordCount: 1800,
    cta: 'Demander un devis',
  },
}

export const allCommunes = [
  'neuilly-sur-seine', 'levallois-perret', 'boulogne-billancourt', 'la-defense',
  'rueil-malmaison', 'saint-cloud', 'issy-les-moulineaux', 'nanterre', 'puteaux',
  'courbevoie', 'suresnes', 'garches', 'la-garenne-colombes', 'vaucresson',
  'montrouge', 'malakoff', 'asnieres-sur-seine', 'colombes', 'clichy',
  'gennevilliers', 'bois-colombes', 'chatillon', 'clamart', 'antony',
  'chatenay-malabry', 'vanves', 'meudon', 'sevres', 'chaville',
  'marnes-la-coquette', 'ville-d-avray', 'bagneux', 'fontenay-aux-roses',
  'le-plessis-robinson', 'sceaux', 'bourg-la-reine',
  'versailles', 'le-chesnay-rocquencourt', 'viroflay', 'velizy-villacoublay',
  'la-celle-saint-cloud', 'bougival', 'jouy-en-josas', 'saint-germain-en-laye',
  'poissy', 'maisons-laffitte', 'conflans-sainte-honorine', 'louveciennes',
  'marly-le-roi', 'le-pecq',
]

export const communes92 = allCommunes.slice(0, 36)
export const communes78 = allCommunes.slice(36)

export function communeToDisplay(slug: string): string {
  const map: Record<string, string> = {
    'neuilly-sur-seine': 'Neuilly-sur-Seine',
    'levallois-perret': 'Levallois-Perret',
    'boulogne-billancourt': 'Boulogne-Billancourt',
    'la-defense': 'La Défense',
    'rueil-malmaison': 'Rueil-Malmaison',
    'saint-cloud': 'Saint-Cloud',
    'issy-les-moulineaux': 'Issy-les-Moulineaux',
    'nanterre': 'Nanterre',
    'puteaux': 'Puteaux',
    'courbevoie': 'Courbevoie',
    'suresnes': 'Suresnes',
    'garches': 'Garches',
    'la-garenne-colombes': 'La Garenne-Colombes',
    'vaucresson': 'Vaucresson',
    'montrouge': 'Montrouge',
    'malakoff': 'Malakoff',
    'asnieres-sur-seine': 'Asnières-sur-Seine',
    'colombes': 'Colombes',
    'clichy': 'Clichy',
    'gennevilliers': 'Gennevilliers',
    'bois-colombes': 'Bois-Colombes',
    'chatillon': 'Châtillon',
    'clamart': 'Clamart',
    'antony': 'Antony',
    'chatenay-malabry': 'Châtenay-Malabry',
    'vanves': 'Vanves',
    'meudon': 'Meudon',
    'sevres': 'Sèvres',
    'chaville': 'Chaville',
    'marnes-la-coquette': 'Marnes-la-Coquette',
    'ville-d-avray': "Ville-d'Avray",
    'bagneux': 'Bagneux',
    'fontenay-aux-roses': 'Fontenay-aux-Roses',
    'le-plessis-robinson': 'Le Plessis-Robinson',
    'sceaux': 'Sceaux',
    'bourg-la-reine': 'Bourg-la-Reine',
    'versailles': 'Versailles',
    'le-chesnay-rocquencourt': 'Le Chesnay-Rocquencourt',
    'viroflay': 'Viroflay',
    'velizy-villacoublay': 'Vélizy-Villacoublay',
    'la-celle-saint-cloud': 'La Celle-Saint-Cloud',
    'bougival': 'Bougival',
    'jouy-en-josas': 'Jouy-en-Josas',
    'saint-germain-en-laye': 'Saint-Germain-en-Laye',
    'poissy': 'Poissy',
    'maisons-laffitte': 'Maisons-Laffitte',
    'conflans-sainte-honorine': 'Conflans-Sainte-Honorine',
    'louveciennes': 'Louveciennes',
    'marly-le-roi': 'Marly-le-Roi',
    'le-pecq': 'Le Pecq',
  }
  return map[slug] || slug.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('-')
}

export function communeNeighbors(slug: string, silo: 'silo-la-defense-92' | 'silo-versailles-78'): string[] {
  const neighbors92: Record<string, string[]> = {
    'neuilly-sur-seine': ['levallois-perret', 'la-defense'],
    'levallois-perret': ['neuilly-sur-seine', 'clichy'],
    'boulogne-billancourt': ['issy-les-moulineaux', 'meudon'],
    'la-defense': ['puteaux', 'courbevoie', 'nanterre'],
    'rueil-malmaison': ['nanterre', 'la-defense'],
    'saint-cloud': ['meudon', 'sevres'],
    'issy-les-moulineaux': ['boulogne-billancourt', 'vanves'],
    'nanterre': ['la-defense', 'rueil-malmaison'],
    'puteaux': ['la-defense', 'courbevoie'],
    'courbevoie': ['la-defense', 'neuilly-sur-seine'],
    'suresnes': ['saint-cloud', 'nanterre'],
    'garches': ['saint-cloud', 'vaucresson'],
    'montrouge': ['malakoff', 'chatillon'],
    'clichy': ['levallois-perret', 'asnieres-sur-seine'],
    'vanves': ['malakoff', 'issy-les-moulineaux'],
    'meudon': ['sevres', 'clamart'],
    'sevres': ['meudon', 'saint-cloud'],
  }
  const neighbors78: Record<string, string[]> = {
    'versailles': ['le-chesnay-rocquencourt', 'viroflay'],
    'le-chesnay-rocquencourt': ['versailles', 'louveciennes'],
    'viroflay': ['versailles', 'le-chesnay-rocquencourt'],
    'velizy-villacoublay': ['versailles', 'jouy-en-josas'],
    'saint-germain-en-laye': ['le-pecq', 'maisons-laffitte'],
    'poissy': ['saint-germain-en-laye', 'conflans-sainte-honorine'],
    'maisons-laffitte': ['saint-germain-en-laye', 'poissy'],
  }
  const map = silo === 'silo-la-defense-92' ? neighbors92 : neighbors78
  return (map[slug] || []).slice(0, 2)
}
