export const siloRegistry = {
  'silo-la-defense-92': {
    pillarUrl: '/gestion-locative-92/',
    pillarEntities: ['La Défense', 'Hauts-de-Seine', 'business traveler', 'clientèle corporate'],
    communes: [
      '/gestion-locative/neuilly-sur-seine/',
      '/gestion-locative/levallois-perret/',
      '/gestion-locative/boulogne-billancourt/',
      '/gestion-locative/la-defense/',
      '/gestion-locative/rueil-malmaison/',
      '/gestion-locative/saint-cloud/',
      '/gestion-locative/issy-les-moulineaux/',
      '/gestion-locative/nanterre/',
      '/gestion-locative/puteaux/',
      '/gestion-locative/courbevoie/',
      '/gestion-locative/suresnes/',
      '/gestion-locative/garches/',
      '/gestion-locative/la-garenne-colombes/',
      '/gestion-locative/vaucresson/',
      '/gestion-locative/montrouge/',
      '/gestion-locative/malakoff/',
      '/gestion-locative/asnieres-sur-seine/',
      '/gestion-locative/colombes/',
      '/gestion-locative/clichy/',
      '/gestion-locative/gennevilliers/',
      '/gestion-locative/bois-colombes/',
      '/gestion-locative/chatillon/',
      '/gestion-locative/clamart/',
      '/gestion-locative/antony/',
      '/gestion-locative/chatenay-malabry/',
      '/gestion-locative/vanves/',
      '/gestion-locative/meudon/',
      '/gestion-locative/sevres/',
      '/gestion-locative/chaville/',
      '/gestion-locative/marnes-la-coquette/',
      '/gestion-locative/ville-d-avray/',
      '/gestion-locative/bagneux/',
      '/gestion-locative/fontenay-aux-roses/',
      '/gestion-locative/le-plessis-robinson/',
      '/gestion-locative/sceaux/',
      '/gestion-locative/bourg-la-reine/',
    ],
  },
  'silo-versailles-78': {
    pillarUrl: '/gestion-locative-78/',
    pillarEntities: ['Versailles', 'Yvelines', 'tourisme international', 'Château de Versailles'],
    communes: [
      '/gestion-locative/versailles/',
      '/gestion-locative/le-chesnay-rocquencourt/',
      '/gestion-locative/viroflay/',
      '/gestion-locative/velizy-villacoublay/',
      '/gestion-locative/la-celle-saint-cloud/',
      '/gestion-locative/bougival/',
      '/gestion-locative/jouy-en-josas/',
      '/gestion-locative/saint-germain-en-laye/',
      '/gestion-locative/poissy/',
      '/gestion-locative/maisons-laffitte/',
      '/gestion-locative/conflans-sainte-honorine/',
      '/gestion-locative/louveciennes/',
      '/gestion-locative/marly-le-roi/',
      '/gestion-locative/le-pecq/',
    ],
  },
  'silo-blog': {
    pillarUrl: '/blog/',
    pillarEntities: ['rentabilité', 'réglementation', 'investissement', 'guide'],
    pages: [
      '/blog/rentabilite-gestion-locative-92/',
      '/blog/reglementation-location-paris-ouest/',
      '/blog/investir-lcd-78/',
      '/blog/tarifs-conciergerie/',
    ],
  },
}

export const interSiloLinks: Record<string, string[]> = {
  '/gestion-locative/saint-cloud/': ['/gestion-locative/versailles/'],
  '/gestion-locative/viroflay/': ['/gestion-locative/meudon/'],
  '/gestion-locative/sevres/': ['/gestion-locative/versailles/'],
  '/gestion-locative/ville-d-avray/': ['/gestion-locative/versailles/'],
}
